### ISSUE TITLE
Loading fixture data via `require` causes crash

### ISSUE THREAD

**Issue by coltdorsey** [annaet/cypress-tags#9]
When loading fixture data via `require` or `import`, this causes the plugin to crash.

`import accounts from '../../fixtures/accounts.json'`
or
`const accounts = require('../../fixtures/accounts.json')`

>  Error running plugin
> 
> The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (/Users/<REDACTED>/project/cypress/plugins/index.js)
> 
> Error: Debug Failure. Output generation failed
>     at Object.transpileModule (/Users/<REDACTED>/node_modules/typescript/lib/typescript.js:129814:29)
>     at DestroyableTransform._flush (/Users/<REDACTED>/node_modules/cypress-tags/node_modules/@cypress/browserify-preprocessor/lib/simple_tsify.js:35:14)
>     at DestroyableTransform.prefinish (/Users/<REDACTED>/node_modules/readable-stream/lib/_stream_transform.js:138:10)
>     at DestroyableTransform.emit (events.js:315:20)
>     at prefinish (/Users/<REDACTED>/node_modules/readable-stream/lib/_stream_writable.js:619:14)
>     at finishMaybe (/Users/<REDACTED>/node_modules/readable-stream/lib/_stream_writable.js:627:5)
>     at endWritable (/Users/<REDACTED>/node_modules/readable-stream/lib/_stream_writable.js:638:3)
>     at DestroyableTransform.Writable.end (/Users/<REDACTED>/node_modules/readable-stream/lib/_stream_writable.js:594:41)
>     at DuplexWrapper.onend (/Users/<REDACTED>/node_modules/readable-stream/lib/_stream_readable.js:577:10)
>     at Object.onceWrapper (events.js:421:28)
>     at DuplexWrapper.emit (events.js:327:22)
>     at endReadableNT (/Users/<REDACTED>/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Stack trace
> Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/<REDACTED>/cypress/plugins/index.js`)
>     at Object.get (/Users/<REDACTED>/Library/Caches/Cypress/6.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:961:15)
>     at EventEmitter.handleError (/Users/<REDACTED>/Library/Caches/Cypress/6.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:159:20)
>     at EventEmitter.emit (events.js:315:20)
>     at ChildProcess.<anonymous> (/Users/<REDACTED>/Library/Caches/Cypress/6.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
>     at ChildProcess.emit (events.js:315:20)
>     at emit (internal/child_process.js:876:12)
>     at processTicksAndRejections (internal/process/task_queues.js:85:21)

**Comment by annaet** [comment]
Hi @coltdorsey, I've been able to recreate the issue locally so will look into this.

**Comment by annaet** [comment]
For now I assume you're aware of the [cy.fixture](https://docs.cypress.io/api/commands/fixture.html#Syntax) syntax that allows you to get access to your fixture from within your tests.

**Comment by coltdorsey** [comment]
@annaet 
Yes, thank you. 

In most cases, cy.fixture works well.
In the case where it doesn't work, is if you want to loop an `it` block with data from a fixture.

```
let accounts

before(() => {
   cy.fixture('../../fixtures/accounts').then((data) => {
       accounts = data
   })
})

// The before() hook is not executed before checking the accounts object, so the accounts object has not been initialized 
// and is therefore undefined.
accounts.forEach((account) => { 
    it('Can't loop tests when using cy.fixture', () => {
       // code
    }) 
})
```

Using import or require to initialize the object was the workaround I had found for the cy.fixture limitation, however this workaround unfortunately causes cypress-tags to crash.

```
const accounts = require('../../fixtures/accounts.json')

// accounts is initialized before looping through accounts object
accounts.forEach((account) => { 
    it('Can loop tests when NOT using cy.fixture', () => {
       // code
    }) 
})
```

**Comment by annaet** [comment]
Hi @coltdorsey - I've just published a new version with a fix in for this (v0.0.18).

Let me know if you encounter anymore issues.

**Comment by coltdorsey** [comment]
@annaet 
Thank you for the fix you made.

I can confirm that the plugin no longer crashes when using the import to load in fixture data.

`import accounts from '../../fixtures/accounts.json'`

However, the plugin does still crash when using require to load in fixture data.

`const accounts = require('../../fixtures/accounts.json')`
